### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by dboyer-ibm** [dboyer-ibm/SEBC#1]

**Comment by dboyer-ibm** [comment]
starting

**Comment by dboyer-ibm** [comment]
CM Install Lab - Prepare EC2 or other instances : 
file 0_nodeIPs.md provided.

**Comment by dboyer-ibm** [comment]
1_preinstall.md

**Comment by dboyer-ibm** [comment]
2_replica_working.md

**Comment by dboyer-ibm** [comment]
labs/3_cm_installed.png

**Comment by dboyer-ibm** [comment]
4_local_repo.png

**Comment by mfernest** [comment]
Marked Incomplete by @rsiwicki
