### ISSUE TITLE
Install CM

### ISSUE THREAD

**Issue by dboyer-ibm** [dboyer-ibm/SEBC#10]
started

**Comment by mfernest** [comment]
See commit [463723f](https://github.com/dboyer-ibm/SEBC/commit/463723fbe168a042453495704eb9ff8503cde6e7)

**Comment by mfernest** [comment]
See [f6b56bd](https://github.com/dboyer-ibm/SEBC/commit/f6b56bdaf9bfe444ead8b6b93bb6182cfd6a2149)
