### ISSUE TITLE
Kerberize cluster

### ISSUE THREAD

**Issue by dboyer-ibm** [dboyer-ibm/SEBC#13]

**Comment by dboyer-ibm** [comment]
The kerberos configuration in cloudera failed.
I then did not have time to find thje origin of this issue.

17/10/20 12:20:30 WARN security.UserGroupInformation: PriviledgedActionException as:ernest (auth:KERBEROS) cause:javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/10/20 12:20:30 WARN ipc.Client: Exception encountered while connecting to the server : javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/10/20 12:20:30 WARN security.UserGroupInformation: PriviledgedActionException as:ernest (auth:KERBEROS) cause:java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
ls: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; Host Details : local host is: "ip-172-31-46-143.eu-west-1.compute.internal/172.31.46.143"; destination host is: "ip-172-31-44-231.eu-west-1.compute.internal":8020;

**Comment by mfernest** [comment]
Required test with Pi not submitted.
