### ISSUE TITLE
Enable Sentry

### ISSUE THREAD

**Issue by dboyer-ibm** [dboyer-ibm/SEBC#14]

**Comment by dboyer-ibm** [comment]
started

**Comment by mfernest** [comment]
No files submitted.

**Comment by dboyer-ibm** [comment]
Hello,

I do not uderstand why this topic was closed as "no files submitted", because the file https://github.com/dboyer-ibm/SEBC/blob/master/security/labs/sentry-test.md does exist. I put the transcipt under each question. For example ;
Question:
##############
Grant read privilege for all tables to reads

    GRANT SELECT ON DATABASE default TO ROLE reads;
    GRANT ROLE reads TO GROUP selector;
###########

###########
Answer :
0: jdbc:hive2://ip-172-31-39-197.eu-west-1.co> GRANT SELECT ON DATABASE default TO ROLE reads;
INFO  : Compiling command(queryId=hive_20171019140909_bfcdffc5-8706-499c-9f23-baa37d30a35e): GRANT SELECT ON DATABASE default TO ROLE reads
INFO  : Semantic Analysis Completed
INFO  : Returning Hive schema: Schema(fieldSchemas:null, properties:null)
INFO  : Completed compiling command(queryId=hive_20171019140909_bfcdffc5-8706-499c-9f23-baa37d30a35e); Time taken: 0.064 seconds
INFO  : Executing command(queryId=hive_20171019140909_bfcdffc5-8706-499c-9f23-baa37d30a35e): GRANT SELECT ON DATABASE default TO ROLE reads
INFO  : Starting task [Stage-0:DDL] in serial mode
INFO  : Completed executing command(queryId=hive_20171019140909_bfcdffc5-8706-499c-9f23-baa37d30a35e); Time taken: 0.038 seconds
INFO  : OK
No rows affected (0.113 seconds)
0: jdbc:hive2://ip-172-31-39-197.eu-west-1.co> GRANT ROLE reads TO GROUP selector;
INFO  : Compiling command(queryId=hive_20171019140909_e8527b69-af9a-4919-abdb-7a79ae3ea7a0): GRANT ROLE reads TO GROUP selector
INFO  : Semantic Analysis Completed
INFO  : Returning Hive schema: Schema(fieldSchemas:null, properties:null)
INFO  : Completed compiling command(queryId=hive_20171019140909_e8527b69-af9a-4919-abdb-7a79ae3ea7a0); Time taken: 0.053 seconds
INFO  : Executing command(queryId=hive_20171019140909_e8527b69-af9a-4919-abdb-7a79ae3ea7a0): GRANT ROLE reads TO GROUP selector
INFO  : Starting task [Stage-0:DDL] in serial mode
INFO  : Completed executing command(queryId=hive_20171019140909_e8527b69-af9a-4919-abdb-7a79ae3ea7a0); Time taken: 0.027 seconds
INFO  : OK
No rows affected (0.093 seconds)
########
