### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by dboyer-ibm** [dboyer-ibm/SEBC#3]

**Comment by dboyer-ibm** [comment]
Replicate to another cluster
The command looked like hadoop distcp hdfs://34.253.82.44/user/rcassiau /user/dboyer
Using internal IPs, this part did not work because of the lack of communication between internal addresses at AMAZON.
Using external IPS, the mapper part worked in local, while the reduce one failed
We think a solution could be to use Amazon VPC, but this will have to be tried later if we have time.
Locally, the distcp worked as expected.

**Comment by dboyer-ibm** [comment]
Test HDFS performance

**Comment by dboyer-ibm** [comment]
Test HDFS Snapshots

**Comment by dboyer-ibm** [comment]
HDFS HA

**Comment by dboyer-ibm** [comment]
http://ec2-52-212-24-11.eu-west-1.compute.amazonaws.com:7180

**Comment by mfernest** [comment]
Marked complete by @rsiwicki
